<a href="https://colab.research.google.com/github/pbhatt48/AlgorithmsLeetCode/blob/main/HackerRank_Numpy_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arrays

A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.

import numpy

a = numpy.array([1,2,3,4,5])
print a[1]          #2

b = numpy.array([1,2,3,4,5],float)
print b[1]          #2.0
In the above example, numpy.array() is used to convert a list into a NumPy array. The second argument (float) can be used to set the type of array elements.

Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format

A single line of input containing space separated numbers.

Output Format

Print the reverse NumPy array with type float.

Sample Input

1 2 3 4 -8 -10
Sample Output

[-10.  -8.   4.   3.   2.   1.]

In [11]:
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    myarr = (np.array(arr[::-1], float))
    print(type(myarr))
    return myarr

arr = np.array([1, 2, 3, 4, -8, -10])
result = arrays(arr)
print(result)

<class 'numpy.ndarray'>
[-10.  -8.   4.   3.   2.   1.]


shape

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

(a). Using shape to get array dimensions

import numpy

my__1D_array = numpy.array([1, 2, 3, 4, 5])
print my_1D_array.shape     #(5,) -> 1 row and 5 columns

my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print my_2D_array.shape     #(3, 2) -> 3 rows and 2 columns 
(b). Using shape to change array dimensions

import numpy

change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print change_array      

#Output
[[1 2]
[3 4]
[5 6]]
reshape

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

import numpy

my_array = numpy.array([1,2,3,4,5,6])
print numpy.reshape(my_array,(3,2))

#Output
[[1 2]
[3 4]
[5 6]]
Task

You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

Input Format

A single line of input containing  space separated integers.

Output Format

Print the X NumPy array.

Sample Input

1 2 3 4 5 6 7 8 9
Sample Output

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [13]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return(numpy.array(arr.reshape(3,3), int))

#arr = input().strip().split(' ')
arr = np.array([1, 2, 3, 4, -8, -10,1,2,3])
result = arrays(numpy.array(arr))
print(result)

[[  1   2   3]
 [  4  -8 -10]
 [  1   2   3]]
